kind: Service
apiVersion: v1
metadata:
  name: flux
  namespace: flux
spec:
  type: LoadBalancer
  selector:
    app: flux
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
